spring:
  main:
    allow-bean-definition-overriding: true
#  application:
#    name: organizationservice
# 开放 动态刷新配置的url 路径 /actuator/refresh
# 默认只有开放 health 和 info
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,hystrix   # refresh 开启动态刷新配置文件 * 开启所有的路径支持
eureka:
  client:
    #    fetch-registry: true  #注册并拉取一份本地缓存
    #    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  #  instance:
  #    prefer-ip-address: true  # 注册服务的ip 而不是主机的名称
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
server:
  port: 8080
# 使用断路器
feign:
  hystrix:
    enabled: true